###############################################################
# Program:
#     Assignment 05, Order Tracking
#     Brother Macbeth, CS165
# Author:
#     Jon Michael Ossola
# Summary:
#     In this project, through the use of many, many 
#     destructors and in line functions, the project
#     determines everything you would need to find out about
#	  in an online store. 
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp address.h address.cpp customer.h customer.cpp order.h order.cpp assign05.cpp
	g++ product.cpp address.cpp customer.cpp order.cpp assign05.cpp

