###############################################################
# Program:
#     Assignment 04, Product inventory
#     Brother Macbeth, CS165
# Author:
#     Jon Michael Ossola
# Summary:
#     The program does the following. In three seperate files,
#     it declares a class with private and public variables, 
#     and then the program takes input from the user regarding
#     a product. The user enters in the information and can 
#     request a reciept, or go through other options like 
#     request a display of inventory.  
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp assign04.cpp
	g++ product.cpp assign04.cpp

